name: Build & Deploy Flutter App to Play Store

on:
  push:
    branches:
      - main # Adjust the branch as needed
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x' # Update to latest stable Flutter version
          cache: true

      - name: Decode and Save Keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/app/upload-keystore.jks

      - name: Setup Keystore in Gradle
        run: |
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}
          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}
          storeFile=upload-keystore.jks
          EOF

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK and AAB
        run: flutter build appbundle

      - name: Decode Google Play JSON Key
        env:
          GOOGLE_PLAY_KEY_JSON: ${{ secrets.GOOGLE_PLAY_KEY_JSON }}
        run: echo "$GOOGLE_PLAY_KEY_JSON" | base64 --decode > google_play_key.json

      - name: Deploy to Play Store (Internal Testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: google_play_key.json
          packageName: com.slconsultech.statusmonitorapp
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed

      - name: Clean Up
        run: rm google_play_key.json



# ANDROID_KEYSTORE_BASE64	The base64 encoded keystore file (upload-keystore.jks).
# ANDROID_KEYSTORE_PASSWORD	The password for the keystore.
# ANDROID_KEY_ALIAS	The key alias name.
# ANDROID_KEY_PASSWORD	The password for the key alias.
# GOOGLE_PLAY_KEY_JSON	The base64 encoded content of google_play_key.json.

# base64 upload-keystore.jks | pbcopy # macOS
# base64 upload-keystore.jks | clip   # Windows
# base64 -w 0 upload-keystore.jks > keystore.b64 # Linux
